export { BannerProfile } from "@/components/BannerProfile";
export { EducationGrid } from "@/components/EducationGrid";
export { Footer } from "@/components/Footer";
export { IntroductorySection } from "@/components/IntroductorySection";
export { KnowledgeCardGrid } from "@/components/KnowledgeCardGrid";
export { PersonalData } from "@/components/PersonalData";
export { PortfolioGrid } from "@/components/PortfolioGrid";
export { SocialMedia } from "@/components/SocialMedia";
export { Main } from "@/components/Main";